# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-24 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('craigapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='category',
            field=models.CharField(default=None, max_length=30),
            preserve_default=False,
        ),
    ]
