# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-24 18:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('craigapp', '0002_subcategory_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='item_price',
        ),
        migrations.AddField(
            model_name='listing',
            name='item_price',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
